image: node:lts-alpine

stages:
  - test
  - dependencies
  - build
  - publish

code quality:
  stage: test
  script:
    - npm ci
    - npm install --save-dev eslint eslint-formatter-gitlab
    - npm run lint -- --format gitlab .
  artifacts:
    reports:
      codequality: gl-codequality.json

test & coverage:
  stage: test
  script:
    - npm ci
    - npm i -D jest-junit
    - npm test -- --ci --reporters=default --reporters=jest-junit
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

outdated:
  stage: dependencies
  script:
    - npm outdated
  allow_failure: true

security scan:
  stage: dependencies
  script:
    # upgrade the NPM version to the latest to be sure
    # the `npm audit` supports the --production flag
    - npm i -g npm
    - npm audit --production
  allow_failure: false

rollup build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 4 weeks

package:
  stage: build
  only:
    - tags
  script:
    - npm pack
  artifacts:
    paths:
      - ./*.tgz

coverage report:
  stage: publish
  dependencies:
    - test & coverage
  script:
    - mv coverage/lcov-report/ public/
  artifacts:
    paths:
      - public
    expire_in: 3 months
  only:
    - master
  environment:
    name: coverage report
    url: https://formschema.gitlab.io/native

publish on npm:
  stage: publish
  needs:
    - package
    - rollup build
  only:
    - tags
    - triggers
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish
  environment:
    name: npm
    url: https://www.npmjs.com/package/@formschema/native
